# ---------- Config with Mods for an example (server.json) ---------- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: reforger-config
  namespace: reforger
data:
  server.json: |
    {
      "publicAddress": "YOUR PUBLIC IP",
      "publicPort": 2001,
      "a2s": { "address": "0.0.0.0", "port": 17777 },
      "game": {
        "name": "YOUR SERVER NAME",
        "password": "",
        "passwordAdmin": "YOUR PASSWORD",
        "admins": [],
        "scenarioId": "{EC7A84CCA33FF66A}Missions/OG_Fallujah_v1.conf",
        "maxPlayers": 128,
        "visible": true,
        "gameProperties": {
          "battlEye": true,
          "fastValidation": true
        },
        "mods": [
          {
          "modId": "666536ED37FD55C3",
          "name": "OldGuys_Fallujah",
          "version": "1.0.14"
          },
          {
          "modId": "5F04F5A0383C44B1",
          "name": "Fallujah Map ByHeine",
          "version": "3.1.13"
          },
          {
          "modId": "5D84C738432BFE6A",
          "name": "WolfsBuildingPack",
          "version": "0.1.56"
          },
          {
          "modId": "5E1735DB431EE29B",
          "name": "Gulfcoast Buildings",
          "version": "1.0.33"
          },
          {
          "modId": "5F0D245931200FD1",
          "name": "Railway Generator",
          "version": "1.0.5"
          },
          {
          "modId": "60B524F7A5AE96A8",
          "name": "ArmaTerrainCore",
          "version": "1.1.6"
          },
          {
          "modId": "6271134D85ED0DDA",
          "name": "ConflictSafezone",
          "version": "1.0.14"
          },
          {
          "modId": "66822B91135F0D6E",
          "name": "OldGuys_Core",
          "version": "1.1.0"
          }
        ]
      }
    }

---
# ---------- Deployment ----------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arma-reforger
  namespace: reforger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arma-reforger
  template:
    metadata:
      labels:
        app: arma-reforger
    spec:
      nodeSelector:
        kubernetes.io/hostname: YOURHOSTNAMEHERE

      # Bind directly to the node's network so your router forwards reach the process
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      initContainers:
        # One-time install/patch of Arma Reforger into persistent /arma
        - name: install-arma
          image: cm2network/steamcmd:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -eux
              mkdir -p /arma
              if [ ! -x /arma/ArmaReforgerServer ]; then
                /home/steam/steamcmd/steamcmd.sh \
                  +@sSteamCmdForcePlatformType linux \
                  +force_install_dir /arma \
                  +login anonymous \
                  +app_update 1874900 validate \
                  +quit
                chmod -R 0777 /arma
              else
                echo "Arma already installed, skipping app_update."
              fi
          volumeMounts:
            - name: gamefiles
              mountPath: /arma

      containers:
        - name: reforger
          image: ghcr.io/acemod/arma-reforger:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -eux
              cd /arma
              exec ./ArmaReforgerServer \
                -config /reforger/Configs/server.json \
                -backendlog -nothrow \
                -profile /home/profile \
                -addonDownloadDir /reforger/workshop \
                -addonsDir /reforger/workshop \
                -maxFPS 60
          ports:
            - name: game
              containerPort: 2001
              protocol: UDP
            - name: a2s
              containerPort: 17777
              protocol: UDP
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: cfg
              mountPath: /reforger/Configs
              readOnly: true
            - name: profile
              mountPath: /home/profile
            - name: workshop
              mountPath: /reforger/workshop
            - name: gamefiles
              mountPath: /arma

      volumes:
        - name: cfg
          configMap:
            name: reforger-config
            items:
              - key: server.json
                path: server.json
        - name: profile
          persistentVolumeClaim:
            claimName: reforger-profile
        - name: workshop
          persistentVolumeClaim:
            claimName: reforger-workshop
        - name: gamefiles
          persistentVolumeClaim:
            claimName: reforger-gamefiles
