apiVersion: v1
kind: Pod
metadata:
  name: sniffer
  namespace: reforger
spec:
  nodeSelector:
    kubernetes.io/hostname: YOURHOSTNAME
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: Never
  containers:
    - name: sniffer
      image: corfr/tcpdump:latest
      # Either privileged:true OR add the two caps below. Keeping both for simplicity.
      securityContext:
        privileged: true
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
      command: ["/bin/sh","-lc"]
      args:
        - tcpdump -n -i any 'udp and (port 2001 or port 17777)'
